server:
  port: 9020
spring:
  application:
    name: gateway-nacos
  cloud: # https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/appendix.html
    gateway:
      default-filters:
        - AddResponseHeader=author,xbw
        - AddRequestParameter=token,${random.uuid}
      routes:
        - id: alibaba-nacos-producer
          uri: lb://alibaba-nacos-producer
          predicates:
            - Path=/api/producer/**
          filters:
            - StripPrefix=2
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848