spring:
  application:
    name: netflix-eureka-consumer
server:
  port: 9003
eureka:
  instance:
    appname: netflix-eureka-consumer
    hostname: 127.0.0.1
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true