spring:
  application:
    name: netflix-eureka-producer
server:
  port: 9001
eureka:
  instance:
    appname: netflix-eureka-producer
    hostname: 127.0.0.1
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
